[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "lgtmeow"
description = "LGTMeow ðŸ¾ â€”â€” ã€Œæœ¬å–µè§‰å¾—å¾ˆä¸é”™ï½žã€"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Nyakku Shigure", email = "sigure.qaq@gmail.com" }]
keywords = ["LGTM", "meow", "LGTMeow", "cli", "emoji-kitchen"]
license = { text = "MIT" }
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
bindings = "bin"
features = ["copy"]
